export const content = {
  ru: {
    nav: ['Главная', 'О нас', 'Услуги', 'Партнёры'],
    languageLabel: 'Язык',
    menuOpen: 'Открыть меню',
    menuClose: 'Закрыть меню',
    heroEyebrow: 'Паломнические туры в Узбекистан',
    heroTitle: 'Путешествия, наполненные духовным смыслом',
    heroText: '',
    heroPrimary: 'Наши услуги',
    heroSecondary: 'О компании',
    heroCaption: '',
    scrollAction: 'Листайте',
    heroServices: ['Авиалогистика', 'Размещение', 'Транспорт', 'Сопровождение'],
    aboutEyebrow: 'О компании',
    aboutTitle: 'SOFINTRAVEL',
    aboutTagline: 'профессиональный организатор паломнических туров',
    presentationAction: 'О нас',
    aboutText: 'SOFINTRAVEL разрабатывает маршруты и координирует каждый этап поездки — от транспортной логистики, размещения и питания до профессионального сопровождения и информационной поддержки, учитывая потребности каждой группы.',
    servicesEyebrow: 'Наши услуги',
    servicesTitle: 'Комплексное туристическое сопровождение',
    services: [
      { title: 'Планирование маршрутов', text: 'Программа, график и потребности группы.' },
      { title: 'Встреча и трансферы', text: 'Прибытие, перемещение и логистика.' },
      { title: 'Размещение и питание', text: 'Гостиничное и ресторанное обслуживание.' },
      { title: 'Экскурсионное сопровождение', text: 'Гиды, аудиогиды и культурная программа.' },
      { title: 'Контроль качества', text: 'Согласованность и внимание к деталям.' },
    ],
    destinationEyebrow: 'Путешествия и впечатления',
    destinationTitle: 'Откройте Узбекистан по-новому',
    destinationText: 'Sofintravel превращает путешествие в знакомство с настоящим Узбекистаном — его историей, архитектурой, культурой и традициями. Мы берём на себя организацию поездки, чтобы вы могли сосредоточиться на впечатлениях, атмосфере и моментах, которые хочется сохранить надолго',
    destinationPoints: ['Духовное наследие', 'Продуманные маршруты', 'Комфортное размещение', 'Транспортная логистика', 'Профессиональные гиды'],
    processEyebrow: 'Почему SOFINTRAVEL',
    processTitle: 'Продуманная организация на каждом этапе поездки',
    process: [
      { title: 'Инфраструктура', text: 'Современная транспортная, гостиничная и сервисная инфраструктура для комфортной организации поездок' },
      { title: 'Планирование', text: 'Маршрут и программа формируются с учётом целей, состава и потребностей группы' },
      { title: 'Сопровождение', text: 'Комплексное сопровождение группы на протяжении всей поездки — от прибытия до завершения программы' },
    ],
    partnersEyebrow: 'Наши партнёры',
    partnerTextOnlyEyebrow: 'ПАРТНЁРСКАЯ СЕТЬ',
    partnersTitle: '',
    partners: [
      { name: 'Qanot Sharq', role: 'Авиационная логистика и групповые перевозки' },
      { name: 'Silk Road Samarkand', role: 'Размещение и туристическая инфраструктура' },
      { name: 'Локальная сеть', role: 'Гиды, транспорт и сервис в Узбекистане' },
    ],
    ctaTitle: 'Путешествия объединяют людей,\nкультуры и возможности',
    copyright: 'Все права защищены.',
  },
  en: {
    nav: ['Home', 'About', 'Services', 'Partners'],
    languageLabel: 'Language',
    menuOpen: 'Open menu',
    menuClose: 'Close menu',
    heroEyebrow: 'Pilgrimage tours in Uzbekistan',
    heroTitle: 'Pilgrimage journeys\nacross Uzbekistan',
    heroText: 'We organize pilgrimage journeys in Uzbekistan: routes, accommodation, transport and group support.',
    heroPrimary: 'Our services',
    heroSecondary: 'About us',
    heroCaption: '',
    scrollAction: 'Explore',
    heroServices: ['Aviation logistics', 'Accommodation', 'Transportation', 'Support'],
    aboutEyebrow: 'About us',
    aboutTitle: 'SOFINTRAVEL',
    aboutTagline: 'More than a journey',
    presentationAction: 'About us',
    aboutText: 'SOFINTRAVEL develops itineraries and coordinates every stage of the journey — from transportation logistics, accommodation and meals to professional assistance and information support — with a focus on the needs of each group.',
    servicesEyebrow: 'Our services',
    servicesTitle: 'Travel organization\nstep by step',
    services: [
      { title: 'Route planning', text: 'Program, schedule and group requirements.' },
      { title: 'Arrival & transfers', text: 'Meet-and-greet, transport and logistics.' },
      { title: 'Accommodation & dining', text: 'Hotel and restaurant service coordination.' },
      { title: 'Excursion support', text: 'Guides, audio guides and cultural programs.' },
      { title: 'Quality control', text: 'Coordination and attention to detail.' },
    ],
    destinationEyebrow: 'Routes and experiences',
    destinationTitle: 'Discover more of Uzbekistan',
    destinationText: 'We create journeys across Uzbekistan that bring cultural and spiritual heritage together with thoughtful logistics, comfort and personal attention.',
    destinationPoints: ['Spiritual heritage', 'Tailored itineraries', 'Comfortable accommodation', 'Transportation logistics', 'Professional guides'],
    processEyebrow: 'Why SOFINTRAVEL',
    processTitle: 'Every stage in trusted hands',
    process: [
      { title: 'Infrastructure', text: 'Trusted partners for flights, accommodation and transport.' },
      { title: 'Planning', text: 'Routes and programs shaped around each group’s needs.' },
      { title: 'Support', text: 'Our team stays with you from arrival to the end of the journey.' },
    ],
    partnersEyebrow: 'Our partners',
    partnerTextOnlyEyebrow: 'PARTNER NETWORK',
    partnersTitle: 'Partners by service area',
    partners: [
      { name: 'Qanot Sharq', role: 'Aviation logistics and group transportation' },
      { name: 'Silk Road Samarkand', role: 'Accommodation and tourism infrastructure' },
      { name: 'Local Network', role: 'Guides, transport and services across Uzbekistan' },
    ],
    ctaTitle: 'Travel connects people,\ncultures and possibilities',
    copyright: 'All rights reserved.',
  },

} as const

export type Locale = keyof typeof content
