export const content = {
  ru: {
    nav: ['Главная', 'О нас', 'Услуги', 'Самарканд', 'Партнёры', 'Презентация'],
    languageLabel: 'Язык',
    menuOpen: 'Открыть меню',
    menuClose: 'Закрыть меню',
    heroEyebrow: 'Паломнические туры в Узбекистане',
    heroTitle: 'Духовные\nпутешествия\nсо смыслом',
    heroText: 'SOFINTRAVEL — профессиональный организатор паломнических поездок по Узбекистану с комплексным сопровождением.',
    heroPrimary: 'Наши услуги',
    heroSecondary: 'О компании',
    heroCaption: 'Самарканд — сердце Великого Шёлкового пути',
    scrollAction: 'Листайте',
    heroServices: ['Авиалогистика', 'Размещение', 'Транспорт', 'Сопровождение'],
    aboutEyebrow: 'О компании',
    aboutTitle: 'SOFINTRAVEL',
    aboutTagline: 'Больше чем путешествия',
    presentationAction: 'Презентация компании',
    aboutText: 'SOFINTRAVEL разрабатывает маршруты и координирует каждый этап поездки — от транспортной логистики, размещения и питания до профессионального сопровождения и информационной поддержки, учитывая потребности каждой группы.',
    servicesEyebrow: 'Наши услуги',
    servicesTitle: 'Комплексный подход\nк вашему путешествию',
    services: [
      { title: 'Планирование маршрутов', text: 'Программа, график и потребности группы.' },
      { title: 'Встреча и трансферы', text: 'Прибытие, перемещение и логистика.' },
      { title: 'Размещение и питание', text: 'Гостиничное и ресторанное обслуживание.' },
      { title: 'Экскурсионное сопровождение', text: 'Гиды, аудиогиды и культурная программа.' },
      { title: 'Контроль качества', text: 'Согласованность и внимание к деталям.' },
    ],
    destinationEyebrow: 'Популярное направление',
    destinationTitle: 'Самарканд',
    destinationText: 'Самарканд объединяет духовное наследие и современную туристическую инфраструктуру. SOFINTRAVEL разработал трёхдневную паломническую программу с комфортным размещением, транспортной логистикой и профессиональным сопровождением.',
    destinationPoints: ['Духовное наследие', 'Трёхдневная программа', 'Комфортное размещение', 'Транспортная логистика', 'Профессиональные гиды'],
    processEyebrow: 'Почему SOFINTRAVEL',
    processTitle: 'Каждый этап под нашим контролем',
    process: [
      { title: 'Инфраструктура', text: 'Надёжные партнёры для перелётов, размещения и транспорта.' },
      { title: 'Планирование', text: 'Маршрут и программа учитывают цели и потребности группы.' },
      { title: 'Сопровождение', text: 'Команда остаётся рядом от прибытия до завершения поездки.' },
    ],
    partnersEyebrow: 'Наши партнёры',
    partnersTitle: 'Партнёрство как основа\nединого сервиса',
    partners: [
      { name: 'Qanot Sharq', role: 'Авиационная логистика и групповые перевозки' },
      { name: 'Silk Road Samarkand', role: 'Размещение и туристическая инфраструктура' },
      { name: 'Local Network', role: 'Гиды, транспорт и сервис в Узбекистане' },
    ],
    ctaTitle: 'Путешествия объединяют людей,\nкультуры и возможности',
    copyright: 'Все права защищены.',
  },
  en: {
    nav: ['Home', 'About', 'Services', 'Samarkand', 'Partners', 'Presentation'],
    languageLabel: 'Language',
    menuOpen: 'Open menu',
    menuClose: 'Close menu',
    heroEyebrow: 'Pilgrimage tours in Uzbekistan',
    heroTitle: 'Spiritual\njourneys\nwith purpose',
    heroText: 'SOFINTRAVEL organizes pilgrimage journeys across Uzbekistan with comprehensive support at every stage.',
    heroPrimary: 'Our services',
    heroSecondary: 'About us',
    heroCaption: 'Samarkand — the heart of the Great Silk Road',
    scrollAction: 'Explore',
    heroServices: ['Aviation logistics', 'Accommodation', 'Transportation', 'Support'],
    aboutEyebrow: 'About us',
    aboutTitle: 'SOFINTRAVEL',
    aboutTagline: 'More than a journey',
    presentationAction: 'Company Presentation',
    aboutText: 'SOFINTRAVEL develops itineraries and coordinates every stage of the journey — from transportation logistics, accommodation and meals to professional assistance and information support — with a focus on the needs of each group.',
    servicesEyebrow: 'Our services',
    servicesTitle: 'A comprehensive approach\nto your journey',
    services: [
      { title: 'Route planning', text: 'Program, schedule and group requirements.' },
      { title: 'Arrival & transfers', text: 'Meet-and-greet, transport and logistics.' },
      { title: 'Accommodation & dining', text: 'Hotel and restaurant service coordination.' },
      { title: 'Excursion support', text: 'Guides, audio guides and cultural programs.' },
      { title: 'Quality control', text: 'Coordination and attention to detail.' },
    ],
    destinationEyebrow: 'Featured destination',
    destinationTitle: 'Samarkand',
    destinationText: 'Samarkand combines spiritual heritage with modern tourism infrastructure. SOFINTRAVEL has developed a three-day pilgrimage program with comfortable accommodation, transportation logistics and professional support.',
    destinationPoints: ['Spiritual heritage', 'Three-day program', 'Comfortable accommodation', 'Transportation logistics', 'Professional guides'],
    processEyebrow: 'Why SOFINTRAVEL',
    processTitle: 'Every stage in trusted hands',
    process: [
      { title: 'Infrastructure', text: 'Trusted partners for flights, accommodation and transport.' },
      { title: 'Planning', text: 'Routes and programs shaped around each group’s needs.' },
      { title: 'Support', text: 'Our team stays with you from arrival to the end of the journey.' },
    ],
    partnersEyebrow: 'Our partners',
    partnersTitle: 'Partnership at the heart\nof a seamless journey',
    partners: [
      { name: 'Qanot Sharq', role: 'Aviation logistics and group transportation' },
      { name: 'Silk Road Samarkand', role: 'Accommodation and tourism infrastructure' },
      { name: 'Local Network', role: 'Guides, transportation and local services' },
    ],
    ctaTitle: 'Travel connects people,\ncultures and possibilities',
    copyright: 'All rights reserved.',
  },
  uz: {
    nav: ['Bosh sahifa', 'Biz haqimizda', 'Xizmatlar', 'Samarqand', 'Hamkorlar', 'Taqdimot'],
    languageLabel: 'Til',
    menuOpen: 'Menyuni ochish',
    menuClose: 'Menyuni yopish',
    heroEyebrow: 'O‘zbekistonda ziyorat sayohatlari',
    heroTitle: 'Mazmunli\nziyorat\nsayohatlari',
    heroText: 'SOFINTRAVEL O‘zbekiston bo‘ylab ziyorat safarlarini har bir bosqichda kompleks hamrohlik bilan tashkil etadi.',
    heroPrimary: 'Xizmatlarimiz',
    heroSecondary: 'Biz haqimizda',
    heroCaption: 'Samarqand — Buyuk Ipak yo‘lining yuragi',
    scrollAction: 'Davom eting',
    heroServices: ['Avialogistika', 'Joylashtirish', 'Transport', 'Hamrohlik'],
    aboutEyebrow: 'Kompaniya haqida',
    aboutTitle: 'SOFINTRAVEL',
    aboutTagline: 'Sayohatdan ham ko‘proq',
    presentationAction: 'Kompaniya taqdimoti',
    aboutText: 'SOFINTRAVEL yo‘nalishlarni ishlab chiqadi va safarning barcha bosqichlarini — transport logistikasi, joylashtirish va ovqatlanishdan professional hamrohlik va axborot ko‘magigacha — muvofiqlashtiradi.',
    servicesEyebrow: 'Xizmatlarimiz',
    servicesTitle: 'Sayohatingizga\nkompleks yondashuv',
    services: [
      { title: 'Yo‘nalishni rejalash', text: 'Dastur, jadval va guruh ehtiyojlari.' },
      { title: 'Kutib olish va transferlar', text: 'Kelish, transport va logistika.' },
      { title: 'Joylashtirish va ovqatlanish', text: 'Mehmonxona va restoran xizmatlari.' },
      { title: 'Ekskursiya hamrohligi', text: 'Gidlar, audiogidlar va madaniy dastur.' },
      { title: 'Sifat nazorati', text: 'Har bir tafsilotga e’tibor va uyg‘unlik.' },
    ],
    destinationEyebrow: 'Mashhur yo‘nalish',
    destinationTitle: 'Samarqand',
    destinationText: 'Samarqand ma’naviy meros va zamonaviy sayyohlik infratuzilmasini birlashtiradi. SOFINTRAVEL qulay joylashtirish, transport logistikasi va professional hamrohlikni qamrab olgan uch kunlik ziyorat dasturini ishlab chiqqan.',
    destinationPoints: ['Ma’naviy meros', 'Uch kunlik dastur', 'Qulay joylashtirish', 'Transport logistikasi', 'Professional gidlar'],
    processEyebrow: 'Nega SOFINTRAVEL',
    processTitle: 'Har bir bosqich e’tiborimizda',
    process: [
      { title: 'Infratuzilma', text: 'Parvoz, joylashtirish va transport uchun ishonchli hamkorlar.' },
      { title: 'Rejalashtirish', text: 'Yo‘nalish va dastur har bir guruh ehtiyojiga moslashtiriladi.' },
      { title: 'Hamrohlik', text: 'Jamoamiz kelishdan safar yakunigacha yoningizda bo‘ladi.' },
    ],
    partnersEyebrow: 'Hamkorlarimiz',
    partnersTitle: 'Yagona xizmat asosida\nishonchli hamkorlik',
    partners: [
      { name: 'Qanot Sharq', role: 'Avialogistika va guruh tashuvlari' },
      { name: 'Silk Road Samarkand', role: 'Joylashtirish va sayyohlik infratuzilmasi' },
      { name: 'Local Network', role: 'Gidlar, transport va mahalliy xizmatlar' },
    ],
    ctaTitle: 'Sayohatlar insonlar, madaniyatlar\nva imkoniyatlarni birlashtiradi',
    copyright: 'Barcha huquqlar himoyalangan.',
  },
} as const

export type Locale = keyof typeof content
